App\Entity\Location:
  properties:
    city:
      - NotBlank: ~
      - Length:
          max: 255
    country:
      - NotBlank: ~
      - Length:
          max: 255
    latitude:
      - NotBlank: ~
      - Range:
          min: -90
          max: 90
    longitude:
      - NotBlank: ~
      - Range:
          min: -180
          max: 180