App\Entity\Measurement:
  properties:
    date:
      - NotBlank: ~
      - Type: \DateTime
    celsius:
      - NotBlank: ~
      - Type: string
      - Range:
          min: -50
          max: 50
    location:
      - NotNull: ~